### ISSUE TITLE
Do you have plan to add testcase each file?

### ISSUE THREAD

**Issue by kgcrom** [diegogub/aranGO#12]
```
aql2.go         aql2_test.go         cursor.go    cursor_test.go
graph.go      graph_test.go      replication.go  replication_test.go
....
```

If yes, I will add testcase and p/r. :blush:

or
Do you have a problem when add testcase each file?

I'm learning Go and studying ArangoDB, so interested in aranGo project.

**Comment by diegogub** [comment]
Hello @kgcrom , that would be nice , it was on my plans for the new 2.5 release. I will be updating the project ,and adding test was one of my plans. I normaly use https://github.com/smartystreets/goconvey/ for test assertion, what do you think?

**Comment by kgcrom** [comment]
Hi @diegogub 
it's cool tool~
when I clone project, read testcase first.
The reason I have created issue is that it was difficult to read simple_test file. ; )

Do I pull requests for now or after 2.5 release?

**Comment by diegogub** [comment]
pull request now into dev branch please, we can rebase on dev branch and work together on it.
