### ISSUE TITLE
Put the JSON2AQL filter feature in a separate package

### ISSUE THREAD

**Issue by solher** [diegogub/aranGO#19]
Hi,
I'm currently writing my own lightweight ArangoDB driver. Just 50 lines to run raw AQL because I don't need all the ORM-like features.
I love your JSON2AQL feature (as I wrote the same thing for SQL) and I'd like to use it in my package.
Could you move the feature in a separate package (or more easily inside a subpackage) ? I will pull request to help you write tests if you want.

I will use it like that:

```go
func AQLFilter(json string) string {
	return aranGO.FilterJSON(json).Generate()
}
```

Thanks for your work !

**Comment by diegogub** [comment]
That's a good Idea! I will do it :) I will keep you updated. I have 2.6 update pending, so I will release both changes. And probably 2.7 ;)
You are welcome!

**Comment by solher** [comment]
Thanks a lot !

**Comment by solher** [comment]
Hum... I've been working all day on the best way of filtering ArangoDB results and I think I'm going to follow another idea than the one I chose at the beginning.

ArangoDB, unlike SQL databases, allows a lot of data formatting inside AQL queries. To the point that when you query: 
```
FOR d
IN documents
RETURN {
    document: d,
    metaData: (
        FOR m
        IN metaData
        FILTER m.documentId == d._id
        RETURN m
    )
}
```

You don't really know what to put the filter on.
I think I'm going to allow JSON filters like that (passed by query parameters from the API client):
```json
{
    "limit": 2,
    "offset": 1,
    "where": {
        "and": [
            {"document._id": "document/4134113213"},
            {"metaData.title": { "neq": "foobar" } }
        ]
    }
}
```

To AQL:
```
LET result = (
    FOR d
    IN documents
    RETURN {
        document: d,
        metaData: (
            FOR m
            IN metaData
            FILTER m.documentId == d._id
            RETURN m
        )
    }
)

FOR var
IN result
LIMIT 1, 2
FILTER var.document._id == "document/4134113213" && var.metaData.title != "foobar"
RETURN var
```

It will not be the prettiest way all the time but I think it is the most powerful and versatile one for the client, and the easiest for the API developer.

**Comment by diegogub** [comment]
I see your point. I will review my code I see If I can improve JSON2AQL, yours is a good idea.
Anyway, I moved orm and aql into 2 sub packages. Branch: json2aql.
regards!

**Comment by solher** [comment]
I just released my driver on GitHub !
I reused the query generator I wrote for SQL, check it out: https://github.com/solher/arangolite
Looks like you're not alone anymore using ArangoDB with Go haha.

Thanks a lot for your work anyway ;)

**Comment by diegogub** [comment]
:D great! :)

**Comment by solher** [comment]
Oh and just one thing. How do you feel about the ArangoDB transaction system ?

To me, the way they force you to write a Javascript function is juste disgusting.
You end up with JS code everywhere inside your Go code.

**Comment by diegogub** [comment]
Yes. same here. I guess we should build some kind of wrapper. But we need to include javascript in Golang driver :( . 
One solution I found quite interesting, is to send JSON to the server, with actions to do in a transaction and data, then build corresponding Fox app to do it server side.
