### ISSUE TITLE
Could you add LICENSE file?

### ISSUE THREAD

**Issue by hnakamur** [diegogub/aranGO#26]
First of all, thanks for creating and sharing a nice software!

Could you add LICENSE file?
The following site may help for choosing a license.
[Choose an open source license - Choose a License](http://choosealicense.com/)

I hope you choose a permissive license like MIT or Apache.
Thanks!

**Comment by diegogub** [comment]
thank you @hnakamur , I will add it. Sorry delay

**Comment by hnakamur** [comment]
Thanks! :+1:

**Comment by diegogub** [comment]
:) Im coding V2 and I will add there it. I will update doc when ready.
Thank you

**Comment by hnakamur** [comment]
I'm glad to hear you're coding V2! I'm looking forward to seeing updated docs.
Thanks!
