### ISSUE TITLE
Tried to create a document but it blocks

### ISSUE THREAD

**Issue by hnakamur** [diegogub/aranGO#28]
I copied the example code at README and modified it.
However when I ran my code, it prints "createAndRelateDocs start" then it blocks at
https://github.com/hnakamur/arangodb_experiment/blob/fc8adf425f94fd1487108da7f1a77e4122f58f21/cmd/example1/main.go#L106-L107

I waited a minute or so, and I gave up.
Could you tell me how to fix the problem?

I user the `root` user to connect to the database.

My environments:

* Ubuntu 16.04 x86_64
* arangodb 3.0.1 installed with apt-get. https://www.arangodb.com/download/ubuntu/
* golang 1.6.2 or 1.7rc1

**Comment by hnakamur** [comment]
I found aranGO depends on https://github.com/diegogub/napping whose license is GPLv3.
This is unacceptable for my use case.
I'm closing this issue now.

**Comment by diegogub** [comment]
HI @hnakamur , I will look other option as http clients with Apache or MIT.

**Comment by hnakamur** [comment]
Hi @diegogub, how about [gentleman](https://github.com/h2non/gentleman) ?

[arangolite](https://github.com/solher/arangolite) uses gentleman.

**Comment by hnakamur** [comment]
FYI, I created [a log plugin](https://github.com/hnakamur/gentleman-log) for [gentleman](https://github.com/h2non/gentleman) after discussion at https://github.com/h2non/gentleman/issues/16.
