### ISSUE TITLE
Connecting to a database other than _system

### ISSUE THREAD

**Issue by revmen** [diegogub/aranGO#36]
I was unable to find an answer to this anywhere in the documentation.

The `Connect` function connects to the default `_system` database and allows you to run queries on any database from there.

I would prefer to connect with a user that does not have access to `_system` and use a database other than `_system`. How do I specify which database to connect to?

If this is not possible, perhaps it should be. It seems dangerous to only allow users to connect who have `_system` access.

**Comment by diegogub** [comment]
Hi @revmen , I see your concern. Currently I'm building v2 branch. So I will change API to add Database option when connecting.
Thanks!

**Comment by diegogub** [comment]
HI @revmen , now in v2 branch you can set default DB to connect before connecting.
Regards!

https://godoc.org/gopkg.in/diegogub/aranGO.v2#SetDefaultDB
