### ISSUE TITLE
Is this driver still actively maintained ?

### ISSUE THREAD

**Issue by sheinbergon** [diegogub/aranGO#41]
Are the latest version ArangoDB supported by it ?

**Comment by diegogub** [comment]
hello @sheinbergon, I'm working on v2 branch to support 3.* ArangoDB version.
If you find anything that it's not supported please let me know
Thanks

**Comment by sheinbergon** [comment]
@diegogub  thanks for responding

So, which version of ArangoDB is most recommended to work with your driver ?
What's the ETA for the V2 release ?

**Comment by diegogub** [comment]
@sheinbergon I'm actually using it v2 and I do not find any issue. http://gopkg.in/diegogub/aranGO.v2
With arango 2.8  and 3.0. I will try to do final test today for 3.1 this weekend or may be during next week
Thanks
