### ISSUE TITLE
Cannot use this library at all

### ISSUE THREAD

**Issue by luisfmelo** [diegogub/aranGO#56]
Hi, I wanted to use your library but something is failing, `github.com/diegogub/napping` is not found.

```
	github.com/diegogub/aranGO imports
	github.com/diegogub/napping: cannot find module providing package github.com/diegogub/napping: module github.com/diegogub/napping
```

**Comment by diegogub** [comment]
Thank you for reporting it, I will take a look at this issue

**Comment by diegogub** [comment]
I need to update the REAME, you should use: gopkg.in/diegogub/arango.v2  

It's updated version of the library.

**Comment by luisfmelo** [comment]
Thanks.
